version: '3.8'

services:

  # Database MySQL per IsySnap Backend
  mysql-isysnap:
    image: mysql:8.0.17
    container_name: isysnap_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isysnap
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - isysnap-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

#  # Backend Spring Boot
#  backend:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    container_name: tablesnap_backend
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-isysnap:3306/isysnap
#      SPRING_DATASOURCE_USERNAME: isysnap_user
#      SPRING_DATASOURCE_PASSWORD: isysnap_password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    depends_on:
#      mysql-isysnap:
#        condition: service_healthy
#    networks:
#      - isysnap-network

# Definizione dei volumi e network
networks:
  isysnap-network:
    driver: bridge

volumes:
  mysql_data: